### ISSUE TITLE
Html content doesn't render to the browser

### ISSUE THREAD

**Issue by Teegreat** [bradtraversy/lead_manager_react_django#38]
The HTML content doesn't render/display any content on the browser. 
It displays the "title" but no "body".

**Comment by mariecolesnic** [comment]
have you solved this problem?

**Comment by DanielScholtz** [comment]
Hi probably you had the same problem as me that we use the newer webpack version which has output-path instead of output and there you dont add the file name at the end of path. First, delete your main.js folder then change the script. 
My script was like this:
`webpack --mode development --watch ./leadmanager/frontend/src/index.js --output-path ./leadmanager/frontend/static/frontend/main.js`
and changed to
`webpack --mode development --watch ./leadmanager/frontend/src/index.js --output-path ./leadmanager/frontend/static/frontend`
after that run `npm run build` and it should generate good now

**Comment by LilianBob** [comment]
> Hi probably you had the same problem as me that we use the newer webpack version which has output-path instead of output and there you dont add the file name at the end of path. First, delete your main.js folder then change the script.
> My script was like this:
> `webpack --mode development --watch ./leadmanager/frontend/src/index.js --output-path ./leadmanager/frontend/static/frontend/main.js`
> and changed to
> `webpack --mode development --watch ./leadmanager/frontend/src/index.js --output-path ./leadmanager/frontend/static/frontend`
> after that run `npm run build` and it should generate good now

I have had partial success with the  above recommendation: 
I changed the "--output" to "--output-path" while retaining the main.js on the path,  which allowed main.js to be build without an error, but the HTML body (APP.js output) still doesn't render.
